# !!!! DO NOT TOUCH !!!
version: "1.1.11"

# Max gens slots a player will have when
# joining the server for the first time
max-gens: 20

# Amount of miliseconds between generators
# dropping items.
# (Will be default value if generator or player does not have an individual value set)
time-inbetween: 5000

# Drop gen items naturally or not naturally
# (Naturally will drop more "random")
drop-gen-naturally: true

# Prevent a generator from spawning any more drops of there is too many entities in a chunk
# (This feature is recommended to prevent lag)
max-chunk-entities:
  enabled: true
  max: 100

# Should the plugins shop be loaded?
shop-enabled: false

# Should the plugins sellsticks be loaded?
# - Remember to add sellsticks into sellstick.yml
#   (It is required to spawn them)
sellstick-enabled: false

# Should the plugins /sell command be loaded?
# (Server restart required to enable/disable)
sell-command-enabled: false

# Should the plugins /shop command be loaded?
# (Server restart required to enable/disable)
shop-command-enabled: false

generators:
  # ############## #
  # Coal Generator #
  # ############## #
  coal:
    next-generator: 'iron'
    upgrade-price: 500
    generator-item:
      type: "173:0"
      name: "&b&lCoal &f&lGenerator"
      lore:
        - ""
        - "&fHøjre-klik for"
        - "&fat placere."
    generator-drops:
      1:
        sell-price: 10
        type: "263:0"
        name: "&b&lCoal"
  # ############## #
  # Iron Generator #
  # ############## #
  iron:
    next-generator: 'gold'
    upgrade-price: 5000
    generator-item:
      type: "42:0"
      name: "&b&lIron &f&lGenerator"
      lore:
        - ""
        - "&fHøjre-klik for"
        - "&fat placere."
    generator-drops:
      1:
        sell-price: 25
        type: "265:0"
        name: "&b&lIron"
  # ############## #
  # Gold Generator #
  # ############## #
  gold:
    next-generator: 'diamond'
    upgrade-price: 10000
    generator-item:
      type: "41:0"
      name: "&b&lGold &f&lGenerator"
      lore:
        - ""
        - "&fHøjre-klik for"
        - "&fat placere."
    generator-drops:
      1:
        sell-price: 35
        type: "266:0"
        name: "&b&lGold"
  # ################# #
  # Diamond Generator #
  # ################# #
  diamond:
    generator-item:
      type: "57:0"
      name: "&b&lDiamond &f&lGenerator"
      lore:
        - ""
        - "&fHøjre-klik for"
        - "&fat placere."
    generator-drops:
      1:
        sell-price: 50
        type: "264:0"
        name: "&b&lDiamond"