name: Generator
version: '${version}'
main: dk.bondegaard.generator.Main
authors: [Bondegaard]
description: Generator plugin
depend:
  - Vault
softdepend:
  - Skript
  - PlaceholderAPI
  - PlotSquared
commands:
  generatoradmin:
    usage: "/generatoradmin <SubCommand>"
    description: "Generator admin command"
    aliases: [gadmin]
